bucket_reso_steps = 64
caption_extension = ".txt"
clip_skip = 1
color_aug = false
dataset_repeats = 10
dynamo_backend = "no"
enable_bucket = true
flip_aug = true
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
in_json = "/home/pure_water_100/kohya_train/sd3_medium_full_11/config/meta_cap.json"
ip_noise_gamma = 0.1
keep_tokens = 2
learning_rate = 9e-5
learning_rate_te1 = 7.5e-7
learning_rate_te2 = 7.5e-7
log_with = "wandb"
logging_dir = "/home/pure_water_100/sd3_medium_full_11/logs"
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_args = []
max_bucket_reso = 1024
max_grad_norm=0.01
max_data_loader_n_workers = 0
max_timestep = 950
max_token_length = 225
max_train_epochs = 30
min_bucket_reso = 256
min_snr_gamma = 5
min_timestep = 50
mixed_precision = "bf16"
multires_noise_discount = 0.1
multires_noise_iterations = 6
no_half_vae = true
noise_offset_type = "Multires"
optimizer_type = "AdamW"
output_dir = "/home/pure_water_100/sd3_medium_full_11/model"
output_name = "sd3_medium_adam_full_finetune_11"
pretrained_model_name_or_path = "/mnt/e/stable-diffusion-3-medium/sd3_medium_incl_clips_t5xxlfp16.safetensors"
resolution = "1024,1024"
sample_every_n_steps = 793
sample_prompts = "/home/pure_water_100/kohya_train/sd3/sd3_medium_full_11/model/prompt.txt"
sample_sampler = "dpmsolver++"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
sdpa = true
seed = 1337
shuffle_caption = false
train_batch_size = 6
train_data_dir = "/mnt/e/datasets/SDXL/full_dataset_neo"
text_encoder_batch_size = 4
train_text_encoder = false
t5xxl_dtype = "bf16"
vae_batch_size = 1
cache_latents = true
cache_latents_to_disk = true
wandb_api_key = ""
wandb_run_name = "sd3_adam_k4s4_11"
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true