bucket_reso_steps = 64
caption_extension = ".txt"
clip_skip = 1
color_aug = true
dataset_repeats = 10
dynamo_backend = "no"
enable_bucket = true
flip_aug = true
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
in_json = "/home/pure_water_100/kohya_train/sdxl/adam_full_extra_06/config/meta_cap.json"
ip_noise_gamma = 0.1
keep_tokens = 2
learning_rate = 1e-5
learning_rate_te1 = 0
learning_rate_te2 = 0
log_with = "wandb"
logging_dir = "/home/pure_water_100/kohya_train/sdxl/adam_full_extra_06/logs"
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 2382
lr_scheduler_args = []
max_bucket_reso = 1024
max_data_loader_n_workers = 0
max_timestep = 950
max_token_length = 225
max_train_epochs = 30
min_bucket_reso = 256
min_snr_gamma = 5
min_timestep = 50
mixed_precision = "bf16"
multires_noise_discount = 0.15
multires_noise_iterations = 8
no_half_vae = true
noise_offset_type = "Multires"
optimizer_args = []
optimizer_type = "AdamW8bit"
output_dir = "/home/pure_water_100/kohya_train/sdxl/adam_full_extra_06/model" 
output_name = "adam_full_finetune_06"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
resolution = "1024,1024"
sample_every_n_steps = 793
sample_prompts = "/home/pure_water_100/kohya_train/sdxl/adam_full_extra_06/model/prompt.txt"
sample_sampler = "dpm_2"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
sdpa = true
seed = 1337
shuffle_caption = true
train_batch_size = 6
train_data_dir = "/mnt/e/datasets/SDXL/full_dataset_neo"
train_text_encoder = false
wandb_api_key = "46aff3d4cebcf43a9afe31c09305fd30153572e6"
wandb_run_name = "adam_full_finetune_06"